### Load in NumPy

In [2]:
import numpy as np 

### Create a NumPy Array 

In [3]:
arr = np.array([1,3,5,7,9])
print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


### Create a Python List

In [4]:
li = [1,3,5,7,9]
print(li)
print(type(li))

[1, 3, 5, 7, 9]
<class 'list'>


### Calculate the execution time in NumPy Array

In [5]:
%timeit np.arange(1,7)**3

3.11 µs ± 667 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Calculate the execution time in Python List 

In [6]:
%timeit [i**3 for i in range(1,7)]

550 ns ± 63.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Get the Dimension 

In [7]:
arr1 = np.array([2,4,6,8])
print(arr1)
print(arr1.ndim)

print()

arr2 = np.array([[2,4,6,8],[1,3,5,7]])
print(arr2)
print(arr2.ndim)

[2 4 6 8]
1

[[2 4 6 8]
 [1 3 5 7]]
2


### Create a three dimensional array 

In [8]:
arr = np.array([[[1,2,3,4],[3,4,5,6],[5,6,7,8]]])
print(arr)
print()
print(arr.ndim)

[[[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]

3


### Create a ten dimensional array 

In [9]:
arr = np.array([10,20,30,40], ndmin = 10)
print(arr)

print()

print(arr.ndim)

[[[[[[[[[[10 20 30 40]]]]]]]]]]

10


### Create an array filled with zeros

In [10]:
arr_z = np.zeros(5)
arr_z1 = np.zeros((3,3))

print(arr_z)
print()
print(arr_z1)

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Create an array filled with ones

In [11]:
arr_o = np.ones(5)
arr_o1 = np.ones((4,3))

print(arr_o)
print()
print(arr_o1)

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Create an empty array 

In [12]:
arr_e = np.empty(5)
print(arr_e)
# the empty array automatically recalls the previous memory's data ! 

[1. 1. 1. 1. 1.]


### Create an ordered array 

In [13]:
arr = np.arange((8))
print(arr)

[0 1 2 3 4 5 6 7]


### Create an array containing ones in diagonal 

In [14]:
arr = np.eye(4,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Use of linspace in an array 

In [15]:
arr = np.linspace(0,20, num=5)
print(arr)

[ 0.  5. 10. 15. 20.]


### Create NumPy Arrays with Random Numbers 

#### rand() function :

In [16]:
# this function is used to generate random values between 0 & 1 

arr1 = np.random.rand(3)
print(arr1)

print()

arr2 = np.random.rand(4,4)
print(arr2)

[0.56592868 0.15126754 0.30359917]

[[0.29827822 0.0958828  0.56177417 0.87246709]
 [0.45815086 0.59341812 0.52945624 0.89010698]
 [0.06782438 0.7888749  0.8014934  0.27164123]
 [0.76667461 0.13918357 0.76198778 0.51369462]]


#### randn() function :

In [17]:
# this function is used to generate random values close to zero (this may return both positive & negative)

arr1 = np.random.randn(3)
print(arr1)

print()

arr2 = np.random.randn(4,4)
print(arr2)

[-0.52912076 -0.24722077  1.32752586]

[[ 0.33756357 -0.10879687  1.6439477   1.28685239]
 [ 0.94723406  0.75306396  0.32131328  1.50910666]
 [-0.29794564  0.6796919   1.1704905   2.26927251]
 [ 1.12833395  1.3600021   1.75965842 -1.49223283]]


#### ranf() function :

In [18]:
# this function is used for doing random sampling in numpy
# It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0)

arr1 = np.random.ranf(5)
print(arr1)

[0.18553913 0.32210961 0.16615055 0.01844231 0.55077092]


#### randint() function : 

In [19]:
# this function is used to generate a random number between any particular given range

arr2 = np.random.randint(1,7,4) # np.random.randint(min_value, max_value, total_values_between_them)
print(arr2)

[1 5 5 4]


### Get Data Type

In [20]:
# integer datatype
arr1 = np.array([1,2,3,4,5,6])
print("Data Type : ", arr1.dtype)

arr_1 = np.array([21548956412,54896874654,4587651684])
print("Data Type : ", arr_1.dtype)

# float datatype
arr2 = np.array([0.1, 1.1, 2.1, 3.3])
print("Data Type : ", arr2.dtype)

# string datatype
arr3 = np.array(['m','a','r','d','a','v'])
print("Data Type : ", arr3.dtype)

# mixed (LGTV HD+)
arr4 = np.array(['i', 13, "punch", 52.3])
print("Data Type : ", arr4.dtype)

Data Type :  int32
Data Type :  int64
Data Type :  float64
Data Type :  <U1
Data Type :  <U32


### Converting data types

In [21]:
arr1 = np.array([1,2,3,4,5])
print("Data Type of",arr1,":", arr1.dtype)

arr2 = np.array([1,2,3,4,5], dtype = np.int16)
print("Data Type of",arr2,":", arr2.dtype)

arr3 = np.array([1,2,3,4,5], dtype = np.int64)
print("Data type of",arr3,":", arr3.dtype)

Data Type of [1 2 3 4 5] : int32
Data Type of [1 2 3 4 5] : int16
Data type of [1 2 3 4 5] : int64


### Converting integer to float values 

In [22]:
arr = np.array([12,2,13,5,7], dtype = "f")
print(arr)
print("Data Type :", arr.dtype)

print()

arr1 = np.array([1,3,5,7,9], dtype = "S")
print(arr1)
print("Data Type : ", arr1.dtype)

# List of characters that are used to represent dtype :

# b - boolean
# c - complex float
# f - float  
# i - integer  
# m - timedelta
# M - datetime
# O - object 
# S - string
# u - unsigned integer
# U - Unicode string 

[12.  2. 13.  5.  7.]
Data Type : float32

[b'1' b'3' b'5' b'7' b'9']
Data Type :  |S1


### Converting using functions 

In [23]:
arr = np.array([1,3,5,7,9])
new_arr = np.float32(arr)
new_new_arr = np.bool_(arr)

print(arr)
print("Data Type :", arr.dtype)

print()

print(new_arr)
print("Data Type :", new_arr.dtype)

print()

print(new_new_arr)
print("Data Type :", new_new_arr.dtype)

[1 3 5 7 9]
Data Type : int32

[1. 3. 5. 7. 9.]
Data Type : float32

[ True  True  True  True  True]
Data Type : bool


### Arithmetic Operations 

#### Addition (a+b) :

In [24]:
arr = np.array([1,2,3,4,5])
add = arr + 3 
print(add)

print()

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
adds = np.add(arr1, arr2) 
print(adds)

[4 5 6 7 8]

[ 2  4  6  8 10]


#### Subtraction (a-b) :

In [25]:
arr = np.array([1,2,3,4,5])
sub = arr - 3 
print(sub)

print()

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
subs = np.subtract(arr1, arr2) 
print(subs)

[-2 -1  0  1  2]

[0 0 0 0 0]


#### Multiplication (a*b) :

In [26]:
arr = np.array([1,2,3,4,5])
mul = arr * 3 
print(mul)

print()

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
mult = np.multiply(arr1, arr2) 
print(mult)

[ 3  6  9 12 15]

[ 1  4  9 16 25]


#### Division (a/b) :

In [27]:
arr = np.array([1,2,3,4,5])
div = arr / 2 
print(div)

print()

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
divs = np.divide(arr1, arr2) 
print(divs)

[0.5 1.  1.5 2.  2.5]

[1. 1. 1. 1. 1.]


#### Modulus (a%b) :

In [28]:
arr = np.array([1,2,3,4,5])
mod = arr % 2 
print(mod)

print()

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
mods = np.mod(arr1, arr2) 
print(mods)

[1 0 1 0 1]

[0 0 0 0 0]


#### Power (a**b) :

In [29]:
arr = np.array([1,2,3,4,5])
pow = arr ** 2 
print(pow)

print()

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
pows = np.power(arr1, arr2) 
print(pows)

[ 1  4  9 16 25]

[   1    4   27  256 3125]


#### Reciprocal (1/a) :

In [30]:
arr = np.array([1,2,3,4,5])
rec = 1 / arr 
print(rec)

print()

arr1 = np.array([1,2,3,4,5])
recp = np.reciprocal(arr1) 
print(recp)

[1.         0.5        0.33333333 0.25       0.2       ]

[1 0 0 0 0]


### Arithmetic Functions 

#### Minimum (min) :

In [31]:
arr = np.array([[2,4,6,8,13],[5,1,3,5,7]])

print("Minimum number:", np.min(arr))
print("Position :", np.argmin(arr))

print() 

print("Minimum numbers from each column :", np.min(arr, axis = 0)) # for column
print("Minimum numbers from each row :", np.min(arr, axis = 1)) # for row 

Minimum number: 1
Position : 6

Minimum numbers from each column : [2 1 3 5 7]
Minimum numbers from each row : [2 1]


#### Maximum (max) :

In [32]:
arr = np.array([[2,4,6,8,13],[5,1,3,5,7]])

print("Maximum number:", np.max(arr))
print("Position :", np.argmax(arr))

print()

print("Maximum numbers from each column :", np.max(arr, axis = 0)) # for column 
print("Maximum numbers from each row :", np.max(arr, axis = 1)) # for row 

Maximum number: 13
Position : 4

Maximum numbers from each column : [ 5  4  6  8 13]
Maximum numbers from each row : [13  7]


#### Square root (sqrt) :

In [33]:
arr = ([4,9,64,144,225,900])

print("Square root :", np.sqrt(arr))

Square root : [ 2.  3.  8. 12. 15. 30.]


#### sin & cos values : 

In [34]:
arr1 = np.array([0,1,6,9,13])
print("sin values :", np.sin(arr1))

print() 

arr2 = np.array([0,1,3,7,11])
print("cos values :", np.cos(arr))

sin values : [ 0.          0.84147098 -0.2794155   0.41211849  0.42016704]

cos values : [-0.65364362 -0.91113026  0.39185723  0.8711474   0.36731937  0.0662467 ]


#### Cumulative Sum (cumsum) :

In [35]:
arr = np.array([1,2,3,4,5]) # cumsum process - [1, 1+2, 1+2+3, 1+2+3+4, 1+2+3+4+5]

print("Cumulative sum :", np.cumsum(arr))

Cumulative sum : [ 1  3  6 10 15]


### Get Shape 

In [36]:
arr = np.array([[1,2,3],[2,4,6]])
print(arr)
print(arr.shape)

print()

arr1= np.array([[[1,2,3],[2,4,6],[7,8,9]]])
print(arr1)
print(arr1.shape)

[[1 2 3]
 [2 4 6]]
(2, 3)

[[[1 2 3]
  [2 4 6]
  [7 8 9]]]
(1, 3, 3)


### Reshape function 

In [37]:
arr1 = np.array([1,3,7,9,11,13,15,17,19])
print(arr1)
print(arr1.ndim)

print() 

# reshaping the one dimensional array into two dimensional array.
re = arr1.reshape(3,3) # reshape(no. of rows, no. of columns)
print(re)
print(re.ndim)

print()

# reshaping again into one dimensional array 
new = re.reshape(-1)
print(new)
print(new.ndim)

[ 1  3  7  9 11 13 15 17 19]
1

[[ 1  3  7]
 [ 9 11 13]
 [15 17 19]]
2

[ 1  3  7  9 11 13 15 17 19]
1


### Indexing in 1D array

In [38]:
arr = np.array([1,3,5,7,9])

# positive indexing
print(arr[2])

# negative indexing
print(arr[-3])

5
5


### Indexing in 2D array

In [39]:
arr = np.array([[9,8,7,6],[5,4,3,2]])

print(arr[0,2]) # positive indexing (here 0 is the index of first array and 2 is the index number of 7 inside that array.)
print()
print(arr[0,-2]) # negative indexing

7

7


### Indexing in 3D array 

In [40]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(arr[0,2,0]) # positive indexing 
print()
print(arr[0,0,0]) # positive indexing
print()
print(arr[0,1,-3]) # negative indexing 

7

1

4


### Slicing in an array 

In [41]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(arr)

print()

print("Get numbers from 3 to 7 :", arr[3:8])
print("Get all numbers after 3 :", arr[4:])
print("Get all numbers till 3 :", arr[:4])

[ 0  1  2  3  4  5  6  7  8  9 10]

Get numbers from 3 to 7 : [3 4 5 6 7]
Get all numbers after 3 : [ 4  5  6  7  8  9 10]
Get all numbers till 3 : [0 1 2 3]


In [42]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

print()

print("Get all Odd numbers :", arr[::2]) # [start:stop:step]
print("Get all even numbers :", arr[1::2]) # [1:_:2] -> 1 is index number running till end & here 2 represents skipping 1/jumping 2
print("Skip 2 numbers between 3 to 8 :", arr[2:9:3])

[1 2 3 4 5 6 7 8 9]

Get all Odd numbers : [1 3 5 7 9]
Get all even numbers : [2 4 6 8]
Skip 2 numbers between 3 to 8 : [3 6 9]


### Slicing in 2D array 

In [43]:
arr = np.array([[1,2,3,4,5,11],[6,7,8,9,13,20]])
print(arr)

print("Get numbers from 1 to 4 :", arr[0,:4])

[[ 1  2  3  4  5 11]
 [ 6  7  8  9 13 20]]
Get numbers from 1 to 4 : [1 2 3 4]


### Iteration of 1D array 

In [44]:
arr = np.array([1,2,3,4,5])

# first method 
print("From first method :")
for i in arr :
    print(i)
    
print()

# second method
print("From second method :")
for j in np.nditer(arr):
    print(j)

From first method :
1
2
3
4
5

From second method :
1
2
3
4
5


### Iteration of 2D array 

In [45]:
arr = np.array([[1,2],[4,5],[7,8]])

for i in arr :
    print(i)

print() 

# first method 
print("From first method :")
for j in arr :
    for k in j :
        print(k)
        
print()        

# second method 
print("From second method :")
for l in np.nditer(arr):
    print(l)

[1 2]
[4 5]
[7 8]

From first method :
1
2
4
5
7
8

From second method :
1
2
4
5
7
8


### Iteration of 3D array 

In [46]:
arr = np.array([[[1,2,3],[5,6,7]]])

for i in arr:
    print(i)
    
print() 

# first method 
print("From first method :")
for j in arr:
    for k in j:
        for l in k:
            print(l)
            
print()

# second method 
print("From second method :")
for m in np.nditer(arr):
    print(m)

[[1 2 3]
 [5 6 7]]

From first method :
1
2
3
5
6
7

From second method :
1
2
3
5
6
7


### Iteration with respect to indexing 

In [47]:
arr = np.array([[1,2,3],[4,5,6]])

for i,j in np.ndenumerate(arr): # ndenumerate function will pass 2 values both for indexing as well as iterate data. 
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


### Copy function vs View function 

#### Similarity : 

In [48]:
arr = np.array([2,4,6,8])
copy = arr.copy()
view = arr.view()

print("Original Array :", arr)

print()

print("Copied Array :", copy)
print("Viewed Array :", view)

Original Array : [2 4 6 8]

Copied Array : [2 4 6 8]
Viewed Array : [2 4 6 8]


#### Difference : 

In [49]:
arr = np.array([9,7,5,3,1])
copy = arr.copy()
view = arr.view()

arr[2] = 60

print("Original Array :", arr)

print()

print("Copied Array :", copy) # it copies the data to the new location resulting in a new array.
print("Viewed Array :", view) # if original data is changed than the viewed one changes too.

Original Array : [ 9  7 60  3  1]

Copied Array : [9 7 5 3 1]
Viewed Array : [ 9  7 60  3  1]


### Joining the Array 

In [50]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

new = np.concatenate((arr1,arr2))
print(new)

[ 1  2  3  4  5  6  7  8  9 10]


In [51]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[5,7,3]])

new1 = np.concatenate((arr1,arr2), axis=0) #columns 
print(new1)

print()

new2 = np.concatenate((arr1,arr2), axis=1) #rows
print(new2)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 7 3]]

[[1 2 3 7 8 9]
 [4 5 6 5 7 3]]


### Splitting the Array 

In [52]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

new1 = np.array_split(arr1,2)
print(new1)

print()

new2 = np.array_split(arr1,5)
print(new2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


### NumPy Array Functions 

#### Search :

In [53]:
arr = np.array([2,3,5,4,9,8,7,1,2,3,5,4,6,2,5,1,3,5,4])

new = np.where(arr == 3)
print(new)

print()

new1 = np.where(arr%2 == 0)
print(new1)

(array([ 1,  9, 16], dtype=int64),)

(array([ 0,  3,  5,  8, 11, 12, 13, 18], dtype=int64),)


#### Sort :

In [54]:
# Integers
arr = np.array([52,2,65,8,41,13,4,9,78,19,1,25,21])
new = np.sort(arr)
print(new)

print()

# String
arr1 = np.array(['m','a','r','d','a','v'])
new1 = np.sort(arr1)
print(new1)

print()

# 2D Array 
arr2 = np.array([[8,9,7],[11,2,5],[13,0,89]])
new2 = np.sort(arr2)
print(new2)

[ 1  2  4  8  9 13 19 21 25 41 52 65 78]

['a' 'a' 'd' 'm' 'r' 'v']

[[ 7  8  9]
 [ 2  5 11]
 [ 0 13 89]]


#### Filter :

In [55]:
arr = np.array([2,99,4,6,8,52,13])
filter = [True, False, True, True, False, True, False]

new = arr[filter]
print(new)

[ 2  4  6 52]


#### Shuffle :

In [56]:
# 1D Array
arr = np.array([10,20,30,40,50,60,70])
np.random.shuffle(arr)
print(arr)

print()

# String
arr2 = np.array(['a','b','c','d','e','f','g','h','i'])
np.random.shuffle(arr2)
print(arr2)

[20 60 40 10 70 50 30]

['i' 'a' 'b' 'f' 'h' 'c' 'd' 'g' 'e']


#### Unique :

In [57]:
# Integers
arr = np.array([1,2,1,2,1,2,3,4,5,6])
uni = np.unique(arr)
print(uni)

print()

# String
arr1 = np.array(['m','a','r','d','a','v','j','a','d','a','u','n'])
uni2 = np.unique(arr1)
print(uni2)

[1 2 3 4 5 6]

['a' 'd' 'j' 'm' 'n' 'r' 'u' 'v']


#### Resize :

In [58]:
arr = np.array([1,2,3,4,5,6])
re = np.resize(arr,(3,2))
print(re)

[[1 2]
 [3 4]
 [5 6]]


#### Insert :

In [59]:
# Inserting data in 1D array.

arr = np.array([1,2,3,4,5])
print(arr)

print()

ins = np.insert(arr, 2 , 30)
print(ins)

ins1 = np.insert(arr, (0,2), 30.5) # cannot insert float or string values in an array containing integers.
print(ins1)

[1 2 3 4 5]

[ 1  2 30  3  4  5]
[30  1  2 30  3  4  5]


In [60]:
# Inserting data in 2D array.

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

print()

ins1 = np.insert(arr, 2, 30, axis=0)
print(ins1)

print()

ins2 = np.insert(arr, 3, [30,40], axis=1)
print(ins2)

[[1 2 3]
 [4 5 6]]

[[ 1  2  3]
 [ 4  5  6]
 [30 30 30]]

[[ 1  2  3 30]
 [ 4  5  6 40]]


In [66]:
# Inserting data through append function.

# 1D Array
arr = np.array([1,2,3,4])
print(arr)

app = np.append(arr, 30)
print(app)

print()

#2D Array
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

app1 = np.append(arr1, [[30,31,32]], axis=0)
print(app1)

[1 2 3 4]
[ 1  2  3  4 30]

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [30 31 32]]


#### Delete 

In [67]:
arr = np.array([13,23,33,43,53,2,63])
print(arr)

dele = np.delete(arr, -2)
print(dele)

[13 23 33 43 53  2 63]
[13 23 33 43 53 63]
