### Load in NumPy

In [2]:
import numpy as np 

### Create a NumPy Array 

In [3]:
arr = np.array([1,3,5,7,9])
print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


### Create a Python List

In [4]:
li = [1,3,5,7,9]
print(li)
print(type(li))

[1, 3, 5, 7, 9]
<class 'list'>


### Calculate the execution time in NumPy Array

In [5]:
%timeit np.arange(1,7)**3

3.48 µs ± 537 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Calculate the execution time in Python List 

In [6]:
%timeit [i**3 for i in range(1,7)]

702 ns ± 99.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Get the Dimension 

In [7]:
arr1 = np.array([2,4,6,8])
print(arr1)
print(arr1.ndim)

print()

arr2 = np.array([[2,4,6,8],[1,3,5,7]])
print(arr2)
print(arr2.ndim)

[2 4 6 8]
1

[[2 4 6 8]
 [1 3 5 7]]
2


### Create a three dimensional array 

In [8]:
arr = np.array([[[1,2,3,4],[3,4,5,6],[5,6,7,8]]])
print(arr)
print()
print(arr.ndim)

[[[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]

3


### Create a ten dimensional array 

In [9]:
arr = np.array([10,20,30,40], ndmin = 10)
print(arr)

print()

print(arr.ndim)

[[[[[[[[[[10 20 30 40]]]]]]]]]]

10


### Create an array filled with zeros

In [10]:
arr_z = np.zeros(5)
arr_z1 = np.zeros((3,3))

print(arr_z)
print()
print(arr_z1)

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Create an array filled with ones

In [11]:
arr_o = np.ones(5)
arr_o1 = np.ones((4,3))

print(arr_o)
print()
print(arr_o1)

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Create an empty array 

In [12]:
arr_e = np.empty(5)
print(arr_e)
# the empty array automatically recalls the previous memory's data ! 

[1. 1. 1. 1. 1.]


### Create an ordered array 

In [13]:
arr = np.arange((8))
print(arr)

[0 1 2 3 4 5 6 7]


### Create an array containing ones in diagonal 

In [14]:
arr = np.eye(4,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Use of linspace in an array 

In [15]:
arr = np.linspace(0,20, num=5)
print(arr)

[ 0.  5. 10. 15. 20.]


### Create NumPy Arrays with Random Numbers 

#### rand() function :

In [16]:
# this function is used to generate random values between 0 & 1 

arr1 = np.random.rand(3)
print(arr1)

print()

arr2 = np.random.rand(4,4)
print(arr2)

[0.70306896 0.12775875 0.08860268]

[[0.98817747 0.23175679 0.14148608 0.5883455 ]
 [0.02833848 0.06474989 0.75713043 0.70042489]
 [0.78880221 0.20717992 0.52782542 0.64124293]
 [0.99605194 0.82750486 0.4668981  0.88604614]]


#### randn() function :

In [17]:
# this function is used to generate random values close to zero (this may return both positive & negative)

arr1 = np.random.randn(3)
print(arr1)

print()

arr2 = np.random.randn(4,4)
print(arr2)

[ 0.47932631  0.98579591 -0.22115582]

[[ 0.51546653  0.71829469  1.44444341  0.97700917]
 [ 0.89949117 -0.55902678  0.43404754  0.59585905]
 [-1.79487249 -1.40750242  0.39952788 -0.50334954]
 [ 0.62998877 -0.50429549 -0.7013177  -0.01946918]]


#### ranf() function :

In [18]:
# this function is used for doing random sampling in numpy
# It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0)

arr1 = np.random.ranf(5)
print(arr1)

[0.51333409 0.16458505 0.59985913 0.23086351 0.7245144 ]


#### randint() function : 

In [19]:
# this function is used to generate a random number between any particular given range

arr2 = np.random.randint(1,7,4) # np.random.randint(min_value, max_value, total_values_between_them)
print(arr2)

[3 4 1 4]


### Get Data Type

In [20]:
# integer datatype
arr1 = np.array([1,2,3,4,5,6])
print("Data Type : ", arr1.dtype)

arr_1 = np.array([21548956412,54896874654,4587651684])
print("Data Type : ", arr_1.dtype)

# float datatype
arr2 = np.array([0.1, 1.1, 2.1, 3.3])
print("Data Type : ", arr2.dtype)

# string datatype
arr3 = np.array(['m','a','r','d','a','v'])
print("Data Type : ", arr3.dtype)

# mixed (LGTV HD+)
arr4 = np.array(['i', 13, "punch", 52.3])
print("Data Type : ", arr4.dtype)

Data Type :  int32
Data Type :  int64
Data Type :  float64
Data Type :  <U1
Data Type :  <U32


### Converting data types

In [21]:
arr1 = np.array([1,2,3,4,5])
print("Data Type of",arr1,":", arr1.dtype)

arr2 = np.array([1,2,3,4,5], dtype = np.int16)
print("Data Type of",arr2,":", arr2.dtype)

arr3 = np.array([1,2,3,4,5], dtype = np.int64)
print("Data type of",arr3,":", arr3.dtype)

Data Type of [1 2 3 4 5] : int32
Data Type of [1 2 3 4 5] : int16
Data type of [1 2 3 4 5] : int64


### Converting integer to float values 

In [22]:
arr = np.array([12,2,13,5,7], dtype = "f")
print(arr)
print("Data Type :", arr.dtype)

print()

arr1 = np.array([1,3,5,7,9], dtype = "S")
print(arr1)
print("Data Type : ", arr1.dtype)

# List of characters that are used to represent dtype :

# b - boolean
# c - complex float
# f - float  
# i - integer  
# m - timedelta
# M - datetime
# O - object 
# S - string
# u - unsigned integer
# U - Unicode string 

[12.  2. 13.  5.  7.]
Data Type : float32

[b'1' b'3' b'5' b'7' b'9']
Data Type :  |S1


### Converting using functions 

In [23]:
arr = np.array([1,3,5,7,9])
new_arr = np.float32(arr)
new_new_arr = np.bool_(arr)

print(arr)
print("Data Type :", arr.dtype)

print()

print(new_arr)
print("Data Type :", new_arr.dtype)

print()

print(new_new_arr)
print("Data Type :", new_new_arr.dtype)

[1 3 5 7 9]
Data Type : int32

[1. 3. 5. 7. 9.]
Data Type : float32

[ True  True  True  True  True]
Data Type : bool


### Arithmetic Operations 

#### Addition (a+b) :

In [26]:
arr = np.array([1,2,3,4,5])
add = arr + 3 
print(add)

print()

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
adds = np.add(arr1, arr2) 
print(adds)

[4 5 6 7 8]

[ 2  4  6  8 10]


#### Subtraction (a-b) :

In [34]:
arr = np.array([1,2,3,4,5])
sub = arr - 3 
print(sub)

print()

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
subs = np.subtract(arr1, arr2) 
print(subs)

[-2 -1  0  1  2]

[0 0 0 0 0]


#### Multiplication (a*b) :

In [35]:
arr = np.array([1,2,3,4,5])
mul = arr * 3 
print(mul)

print()

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
mult = np.multiply(arr1, arr2) 
print(mult)

[ 3  6  9 12 15]

[ 1  4  9 16 25]


#### Division (a/b) :

In [36]:
arr = np.array([1,2,3,4,5])
div = arr / 2 
print(div)

print()

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
divs = np.divide(arr1, arr2) 
print(divs)

[0.5 1.  1.5 2.  2.5]

[1. 1. 1. 1. 1.]


#### Modulus (a%b) :

In [37]:
arr = np.array([1,2,3,4,5])
mod = arr % 2 
print(mod)

print()

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
mods = np.mod(arr1, arr2) 
print(mods)

[1 0 1 0 1]

[0 0 0 0 0]


#### Power (a**b) :

In [38]:
arr = np.array([1,2,3,4,5])
pow = arr ** 2 
print(pow)

print()

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
pows = np.power(arr1, arr2) 
print(pows)

[ 1  4  9 16 25]

[   1    4   27  256 3125]


#### Reciprocal (1/a) :

In [41]:
arr = np.array([1,2,3,4,5])
rec = 1 / arr 
print(rec)

print()

arr1 = np.array([1,2,3,4,5])
recp = np.reciprocal(arr1) 
print(recp)

[1.         0.5        0.33333333 0.25       0.2       ]

[1 0 0 0 0]
