### Load in NumPy

In [50]:
import numpy as np 

### Create a NumPy Array 

In [51]:
arr = np.array([1,3,5,7,9])
print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


### Create a Python List

In [52]:
li = [1,3,5,7,9]
print(li)
print(type(li))

[1, 3, 5, 7, 9]
<class 'list'>


### Calculate the execution time in NumPy Array

In [53]:
%timeit np.arange(1,7)**3

3.27 µs ± 750 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Calculate the execution time in Python List 

In [54]:
%timeit [i**3 for i in range(1,7)]

582 ns ± 112 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Get the Dimension 

In [55]:
arr1 = np.array([2,4,6,8])
print(arr1)
print(arr1.ndim)

print()

arr2 = np.array([[2,4,6,8],[1,3,5,7]])
print(arr2)
print(arr2.ndim)

[2 4 6 8]
1

[[2 4 6 8]
 [1 3 5 7]]
2


### Create a three dimensional array 

In [56]:
arr = np.array([[[1,2,3,4],[3,4,5,6],[5,6,7,8]]])
print(arr)
print()
print(arr.ndim)

[[[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]

3


### Create a ten dimensional array 

In [57]:
arr = np.array([10,20,30,40], ndmin = 10)
print(arr)

print()

print(arr.ndim)

[[[[[[[[[[10 20 30 40]]]]]]]]]]

10


### Create an array filled with zeros

In [58]:
arr_z = np.zeros(5)
arr_z1 = np.zeros((3,3))

print(arr_z)
print()
print(arr_z1)

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Create an array filled with ones

In [59]:
arr_o = np.ones(5)
arr_o1 = np.ones((4,3))

print(arr_o)
print()
print(arr_o1)

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Create an empty array 

In [60]:
arr_e = np.empty(5)
print(arr_e)
# the empty array automatically recalls the previous memory's data ! 

[1. 1. 1. 1. 1.]


### Create an ordered array 

In [61]:
arr = np.arange((8))
print(arr)

[0 1 2 3 4 5 6 7]


### Create an array containing ones in diagonal 

In [62]:
arr = np.eye(4,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Use of linspace in an array 

In [63]:
arr = np.linspace(0,20, num=5)
print(arr)

[ 0.  5. 10. 15. 20.]


### Create NumPy Arrays with Random Numbers 

#### rand() function :

In [64]:
# this function is used to generate random values between 0 & 1 

arr1 = np.random.rand(3)
print(arr1)

print()

arr2 = np.random.rand(4,4)
print(arr2)

[0.93015505 0.7619932  0.503953  ]

[[0.53467209 0.45533246 0.93974116 0.43994673]
 [0.17434144 0.77485876 0.14339103 0.84340169]
 [0.17481499 0.81505601 0.4981963  0.66027621]
 [0.43409704 0.82218946 0.26949285 0.47817865]]


#### randn() function :

In [65]:
# this function is used to generate random values close to zero (this may return both positive & negative)

arr1 = np.random.randn(3)
print(arr1)

print()

arr2 = np.random.randn(4,4)
print(arr2)

[1.64211623 0.22845573 1.0147357 ]

[[ 0.53325899  2.28379711  1.13792728  0.18915079]
 [ 0.27014887 -0.98851342  1.37276896 -0.19151441]
 [-3.10523474  0.23758849  0.29599935  1.26710628]
 [ 0.6752073   0.86861344 -0.04716036 -0.93881331]]


#### ranf() function :

In [66]:
# this function is used for doing random sampling in numpy
# It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0)

arr1 = np.random.ranf(5)
print(arr1)

[0.4891743  0.67484378 0.05985335 0.81256104 0.03701307]


#### randint() function : 

In [67]:
# this function is used to generate a random number between any particular given range

arr2 = np.random.randint(1,7,4) # np.random.randint(min_value, max_value, total_values_between_them)
print(arr2)

[4 3 6 1]


### Get Data Type

In [68]:
# integer datatype
arr1 = np.array([1,2,3,4,5,6])
print("Data Type : ", arr1.dtype)

arr_1 = np.array([21548956412,54896874654,4587651684])
print("Data Type : ", arr_1.dtype)

# float datatype
arr2 = np.array([0.1, 1.1, 2.1, 3.3])
print("Data Type : ", arr2.dtype)

# string datatype
arr3 = np.array(['m','a','r','d','a','v'])
print("Data Type : ", arr3.dtype)

# mixed (LGTV HD+)
arr4 = np.array(['i', 13, "punch", 52.3])
print("Data Type : ", arr4.dtype)

Data Type :  int32
Data Type :  int64
Data Type :  float64
Data Type :  <U1
Data Type :  <U32


### Converting data types

In [92]:
arr1 = np.array([1,2,3,4,5])
print("Data Type of",arr1,":", arr1.dtype)

arr2 = np.array([1,2,3,4,5], dtype = np.int16)
print("Data Type of",arr2,":", arr2.dtype)

arr3 = np.array([1,2,3,4,5], dtype = np.int64)
print("Data type of",arr3,":", arr3.dtype)

Data Type of [1 2 3 4 5] : int32
Data Type of [1 2 3 4 5] : int16
Data type of [1 2 3 4 5] : int64


### Converting integer to float values 

In [93]:
arr = np.array([12,2,13,5,7], dtype = "f")
print(arr)
print("Data Type :", arr.dtype)

# List of characters that are used to represent dtype :

# b - boolean
# c - complex float
# f - float  
# i - integer  
# m - timedelta
# M - datetime
# O - object 
# S - string
# u - unsigned integer
# U - Unicode string 

[12.  2. 13.  5.  7.]
Data Type : float32


### Converting using functions 

In [94]:
arr = np.array([1,3,5,7,9])
new_arr = np.float32(arr)
new_new_arr = np.bool_(arr)

print(arr)
print("Data Type :", arr.dtype)

print()

print(new_arr)
print("Data Type :", new_arr.dtype)

print()

print(new_new_arr)
print("Data Type :", new_new_arr.dtype)

[1 3 5 7 9]
Data Type : int32

[1. 3. 5. 7. 9.]
Data Type : float32

[ True  True  True  True  True]
Data Type : bool
