### Load in NumPy

In [2]:
import numpy as np 

### Create a NumPy Array 

In [4]:
arr = np.array([1,3,5,7,9])
print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


### Create a Python List

In [6]:
li = [1,3,5,7,9]
print(li)
print(type(li))

[1, 3, 5, 7, 9]
<class 'list'>


### Calculate the execution time in NumPy Array

In [7]:
%timeit np.arange(1,7)**3

2.76 µs ± 361 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Calculate the execution time in Python List 

In [9]:
%timeit [i**3 for i in range(1,7)]

632 ns ± 71.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Get the Dimension 

In [14]:
arr1 = np.array([2,4,6,8])
print(arr1)
print(arr1.ndim)

print()

arr2 = np.array([[2,4,6,8],[1,3,5,7]])
print(arr2)
print(arr2.ndim)

[2 4 6 8]
1

[[2 4 6 8]
 [1 3 5 7]]
2


### Create a three dimensional array 

In [16]:
arr = np.array([[[1,2,3,4],[3,4,5,6],[5,6,7,8]]])
print(arr)
print()
print(arr.ndim)

[[[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]

3


### Create a ten dimensional array 

In [18]:
arr = np.array([10,20,30,40], ndmin = 10)
print(arr)

print()

print(arr.ndim)

[[[[[[[[[[10 20 30 40]]]]]]]]]]

10


### Create an array filled with zeros

In [20]:
arr_z = np.zeros(5)
arr_z1 = np.zeros((3,3))

print(arr_z)
print()
print(arr_z1)

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Create an array filled with ones

In [21]:
arr_o = np.ones(5)
arr_o1 = np.ones((4,3))

print(arr_o)
print()
print(arr_o1)

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Create an empty array 

In [23]:
arr_e = np.empty(5)
print(arr_e)
# the empty array automatically recalls the previous memory's data ! 

[1. 1. 1. 1. 1.]


### Create an ordered array 

In [26]:
arr = np.arange((8))
print(arr)

[0 1 2 3 4 5 6 7]


### Create an array containing ones in diagonal 

In [27]:
arr = np.eye(4,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Use of linspace in an array 

In [29]:
arr = np.linspace(0,20, num=5)
print(arr)

[ 0.  5. 10. 15. 20.]
