### Load in NumPy

In [2]:
import numpy as np 

### Create a NumPy Array 

In [4]:
arr = np.array([1,3,5,7,9])
print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


### Create a Python List

In [6]:
li = [1,3,5,7,9]
print(li)
print(type(li))

[1, 3, 5, 7, 9]
<class 'list'>


### Calculate the execution time in NumPy Array

In [7]:
%timeit np.arange(1,7)**3

2.76 µs ± 361 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Calculate the execution time in Python List 

In [9]:
%timeit [i**3 for i in range(1,7)]

632 ns ± 71.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Get the Dimension 

In [14]:
arr1 = np.array([2,4,6,8])
print(arr1)
print(arr1.ndim)

print()

arr2 = np.array([[2,4,6,8],[1,3,5,7]])
print(arr2)
print(arr2.ndim)

[2 4 6 8]
1

[[2 4 6 8]
 [1 3 5 7]]
2
